// Data contoh (mock) untuk demo - nanti diganti dengan data dari Supabase

export const mockAnimals = [
  {
    id: '1',
    name: 'Esme and Ralda',
    breed: 'Persian Mix',
    age: 2,
    weight: 4.5,
    height: 25,
    color: 'Abu-abu & Putih',
    gender: 'Betina',
    description: 'Dua kucing kembar yang sangat jinak dan suka bermain. Mereka selalu bersama dan sangat cocok untuk keluarga yang ingin mengadopsi dua kucing sekaligus. Sudah terlatih menggunakan litter box.',
    health_status: 'Sehat',
    vaccinated: true,
    vaccination_date: '2024-01-15',
    disease_history: 'Tidak ada',
    status: 'available',
    category: 'Kucing',
    category_id: 1,
    shelter_id: '1',
    shelter_name: 'Jakarta Pet Shelter',
    location: 'Jakarta Selatan',
    views_count: 245,
    favorites_count: 32,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-green-400',
  },
  {
    id: '2',
    name: 'Layla',
    breed: 'Golden Retriever',
    age: 3,
    weight: 28,
    height: 55,
    color: 'Emas',
    gender: 'Betina',
    description: 'Layla adalah anjing yang sangat ramah dan energik. Dia sangat suka bermain fetch dan berenang. Sangat cocok untuk keluarga aktif yang suka berolahraga di luar ruangan.',
    health_status: 'Sehat',
    vaccinated: true,
    vaccination_date: '2024-02-20',
    disease_history: 'Tidak ada',
    status: 'available',
    category: 'Anjing',
    category_id: 2,
    shelter_id: '1',
    shelter_name: 'Jakarta Pet Shelter',
    location: 'Jakarta Selatan',
    views_count: 389,
    favorites_count: 67,
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-amber-400',
  },
  {
    id: '3',
    name: 'Brown',
    breed: 'French Bulldog',
    age: 1,
    weight: 12,
    height: 30,
    color: 'Coklat Muda',
    gender: 'Jantan',
    description: 'Brown adalah French Bulldog yang lucu dan penuh kasih sayang. Ukurannya compact sehingga cocok untuk apartemen. Sangat suka tidur di pangkuan pemiliknya.',
    health_status: 'Sehat',
    vaccinated: true,
    vaccination_date: '2024-03-10',
    disease_history: 'Tidak ada',
    status: 'available',
    category: 'Anjing',
    category_id: 2,
    shelter_id: '2',
    shelter_name: 'Bandung Animal Care',
    location: 'Bandung',
    views_count: 512,
    favorites_count: 89,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-cyan-400',
  },
  {
    id: '4',
    name: 'Roy',
    breed: 'Corgi',
    age: 2,
    weight: 13,
    height: 27,
    color: 'Oranye & Putih',
    gender: 'Jantan',
    description: 'Roy adalah Corgi yang sangat ceria dan aktif. Kakinya yang pendek membuatnya terlihat sangat menggemaskan saat berlari. Dia sangat patuh dan mudah dilatih.',
    health_status: 'Sehat',
    vaccinated: true,
    vaccination_date: '2024-01-25',
    disease_history: 'Tidak ada',
    status: 'available',
    category: 'Anjing',
    category_id: 2,
    shelter_id: '3',
    shelter_name: 'Surabaya Pet House',
    location: 'Surabaya',
    views_count: 298,
    favorites_count: 45,
    image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-orange-400',
  },
  {
    id: '5',
    name: 'Kristen',
    breed: 'British Shorthair',
    age: 4,
    weight: 5,
    height: 28,
    color: 'Coklat Tabby',
    gender: 'Betina',
    description: 'Kristen adalah kucing yang tenang dan mandiri. Dia suka berjemur di dekat jendela dan bermain dengan bola benang. Sangat cocok untuk pemilik yang tinggal sendiri.',
    health_status: 'Sehat',
    vaccinated: true,
    vaccination_date: '2024-04-05',
    disease_history: 'Tidak ada',
    status: 'available',
    category: 'Kucing',
    category_id: 1,
    shelter_id: '2',
    shelter_name: 'Bandung Animal Care',
    location: 'Bandung',
    views_count: 176,
    favorites_count: 28,
    image: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-amber-300',
  },
  {
    id: '6',
    name: 'Jack',
    breed: 'Jack Russell Terrier',
    age: 1,
    weight: 7,
    height: 30,
    color: 'Putih & Coklat',
    gender: 'Jantan',
    description: 'Jack adalah anjing kecil yang penuh energi. Dia sangat suka bermain dan berlari di taman. Cocok untuk keluarga dengan anak-anak yang aktif.',
    health_status: 'Sehat',
    vaccinated: true,
    vaccination_date: '2024-02-14',
    disease_history: 'Tidak ada',
    status: 'available',
    category: 'Anjing',
    category_id: 2,
    shelter_id: '1',
    shelter_name: 'Jakarta Pet Shelter',
    location: 'Jakarta Selatan',
    views_count: 201,
    favorites_count: 35,
    image: 'https://images.unsplash.com/photo-1593134257782-e89567b7718a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1593134257782-e89567b7718a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-rose-300',
  },
  {
    id: '7',
    name: 'Tweety',
    breed: 'Cockatiel',
    age: 1,
    weight: 0.09,
    height: 30,
    color: 'Kuning & Abu-abu',
    gender: 'Jantan',
    description: 'Tweety adalah cockatiel yang pintar dan bisa menirukan suara. Dia suka bersiul dan sangat jinak karena sudah dilatih sejak kecil.',
    health_status: 'Sehat',
    vaccinated: false,
    vaccination_date: null,
    disease_history: 'Tidak ada',
    status: 'available',
    category: 'Burung',
    category_id: 3,
    shelter_id: '3',
    shelter_name: 'Surabaya Pet House',
    location: 'Surabaya',
    views_count: 134,
    favorites_count: 19,
    image: 'https://images.unsplash.com/photo-1552728089-57168db284ee?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1552728089-57168db284ee?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-yellow-400',
  },
  {
    id: '8',
    name: 'Bunny',
    breed: 'Holland Lop',
    age: 1,
    weight: 1.8,
    height: 15,
    color: 'Putih',
    gender: 'Betina',
    description: 'Bunny adalah kelinci Holland Lop yang sangat lembut dan tenang. Telinganya yang turun membuatnya terlihat sangat menggemaskan. Cocok untuk anak-anak.',
    health_status: 'Sehat',
    vaccinated: true,
    vaccination_date: '2024-03-20',
    disease_history: 'Tidak ada',
    status: 'adopted',
    category: 'Kelinci',
    category_id: 4,
    shelter_id: '2',
    shelter_name: 'Bandung Animal Care',
    location: 'Bandung',
    views_count: 267,
    favorites_count: 41,
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-pink-300',
  },
  {
    id: '9',
    name: 'Hammy',
    breed: 'Syrian Hamster',
    age: 0.5,
    weight: 0.15,
    height: 8,
    color: 'Coklat Keemasan',
    gender: 'Jantan',
    description: 'Hammy adalah hamster yang aktif di malam hari. Dia suka berlari di roda hamster dan menyimpan makanan di pipinya yang mengembung lucu.',
    health_status: 'Sehat',
    vaccinated: false,
    vaccination_date: null,
    disease_history: 'Tidak ada',
    status: 'available',
    category: 'Hamster',
    category_id: 5,
    shelter_id: '1',
    shelter_name: 'Jakarta Pet Shelter',
    location: 'Jakarta Selatan',
    views_count: 89,
    favorites_count: 12,
    image: 'https://images.unsplash.com/photo-1425082661507-d6d2f66e40e1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1425082661507-d6d2f66e40e1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
    bgColor: 'bg-amber-200',
  },
]

export const mockShelters = [
  {
    id: '1',
    name: 'Jakarta Pet Shelter',
    description: 'Shelter hewan terbesar di Jakarta dengan fasilitas lengkap. Kami merawat berbagai jenis hewan yang membutuhkan rumah baru. Tim dokter hewan profesional siap melayani.',
    address: 'Jl. Kemang Raya No. 45, Kemang',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    phone: '021-7654321',
    email: 'info@jakartapetshelter.com',
    website: 'www.jakartapetshelter.com',
    logo_url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    verified: true,
    operating_hours: { senin_jumat: '08:00 - 17:00', sabtu: '08:00 - 14:00', minggu: 'Tutup' },
    animal_count: 45,
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Bandung Animal Care',
    description: 'Pusat perawatan dan adopsi hewan di Bandung. Kami fokus pada rehabilitasi hewan terlantar dan mencarikan mereka keluarga baru yang penuh kasih sayang.',
    address: 'Jl. Dago Atas No. 120',
    city: 'Bandung',
    province: 'Jawa Barat',
    phone: '022-1234567',
    email: 'hello@bandunganimalcare.com',
    website: 'www.bandunganimalcare.com',
    logo_url: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    verified: true,
    operating_hours: { senin_jumat: '09:00 - 16:00', sabtu: '09:00 - 13:00', minggu: 'Tutup' },
    animal_count: 32,
    rating: 4.6,
  },
  {
    id: '3',
    name: 'Surabaya Pet House',
    description: 'Rumah penampungan hewan di Surabaya yang telah beroperasi sejak 2015. Kami menyediakan layanan adopsi, vaksinasi, dan edukasi tentang perawatan hewan.',
    address: 'Jl. Darmo Permai No. 88',
    city: 'Surabaya',
    province: 'Jawa Timur',
    phone: '031-9876543',
    email: 'contact@surabayapethouse.com',
    website: 'www.surabayapethouse.com',
    logo_url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80',
    verified: true,
    operating_hours: { senin_jumat: '08:30 - 16:30', sabtu: '08:30 - 12:00', minggu: 'Tutup' },
    animal_count: 28,
    rating: 4.5,
  },
]

export const mockArticles = [
  {
    id: '1',
    title: 'Tips Merawat Burung Peliharaan untuk Pemula',
    slug: 'tips-merawat-burung',
    category: 'Perawatan Hewan',
    excerpt: 'Panduan lengkap untuk Anda yang baru pertama kali memelihara burung. Mulai dari memilih sangkar, jenis makanan, hingga cara menjaga kesehatannya.',
    content: `Memelihara burung bisa menjadi pengalaman yang sangat menyenangkan. Burung adalah hewan peliharaan yang cerdas, cantik, dan bisa memberikan hiburan dengan kicauannya.\n\n## Memilih Sangkar yang Tepat\nPastikan sangkar cukup besar agar burung bisa mengepakkan sayapnya dengan bebas. Letakkan sangkar di tempat yang mendapat cahaya matahari pagi.\n\n## Nutrisi yang Seimbang\nBerikan pakan yang bervariasi: biji-bijian, buah-buahan segar, dan sayuran. Jangan lupa sediakan air minum bersih setiap hari.\n\n## Kebersihan\nBersihkan sangkar secara rutin minimal seminggu sekali. Ganti alas sangkar dan cuci wadah makan minum.\n\n## Interaksi\nAjak burung Anda berinteraksi setiap hari. Bicara dengan suara lembut dan latih dengan sabar.`,
    thumbnail_url: 'https://images.unsplash.com/photo-1552728089-57168db284ee?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    author: 'Dr. Rina Wijaya',
    published: true,
    views_count: 1250,
    created_at: '2024-09-15',
  },
  {
    id: '2',
    title: 'Panduan Adopsi Hewan Eksotis: Yang Perlu Diketahui',
    slug: 'panduan-adopsi-hewan-eksotis',
    category: 'Tips Adopsi',
    excerpt: 'Ingin mengadopsi hewan eksotis seperti landak mini atau sugar glider? Baca panduan lengkap ini sebelum memutuskan.',
    content: `Mengadopsi hewan eksotis memerlukan persiapan yang lebih matang dibandingkan hewan peliharaan konvensional.\n\n## Riset Terlebih Dahulu\nPelajari karakteristik hewan, kebutuhan nutrisi, dan habitatnya. Pastikan Anda mampu menyediakan lingkungan yang sesuai.\n\n## Legalitas\nPastikan hewan yang ingin Anda adopsi legal untuk dipelihara di Indonesia.\n\n## Dokter Hewan Spesialis\nCari dokter hewan yang memiliki pengalaman menangani hewan eksotis.\n\n## Biaya Perawatan\nHewan eksotis umumnya membutuhkan biaya perawatan yang lebih tinggi.`,
    thumbnail_url: 'https://images.unsplash.com/photo-1559828456-a496b055d7f1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    author: 'Ahmad Fauzi',
    published: true,
    views_count: 890,
    created_at: '2024-09-20',
  },
  {
    id: '3',
    title: 'Cara Melatih Anak Anjing: Panduan Lengkap',
    slug: 'cara-melatih-anak-anjing',
    category: 'Perawatan Hewan',
    excerpt: 'Pelatihan sejak dini sangat penting untuk membentuk perilaku anjing yang baik. Simak tips dan trik melatih anak anjing Anda.',
    content: `Melatih anak anjing memerlukan kesabaran dan konsistensi. Berikut panduan lengkap yang bisa Anda ikuti.\n\n## Mulai dari Dasar\nAjarkan perintah dasar seperti "duduk", "diam", dan "kemari". Gunakan hadiah berupa snack untuk reward.\n\n## Toilet Training\nBawa anjing keluar secara rutin, terutama setelah makan dan bangun tidur.\n\n## Sosialisasi\nPerkenalkan anjing Anda dengan orang lain dan hewan lain sejak dini agar mereka terbiasa.\n\n## Konsistensi\nGunakan perintah yang sama dan pastikan semua anggota keluarga mengikuti aturan yang sama.`,
    thumbnail_url: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    author: 'Budi Santoso',
    published: true,
    views_count: 2100,
    created_at: '2024-10-01',
  },
  {
    id: '4',
    title: 'Vaksinasi Kucing: Jadwal dan Jenis yang Wajib',
    slug: 'vaksinasi-kucing',
    category: 'Kesehatan Hewan',
    excerpt: 'Ketahui jadwal vaksinasi kucing yang tepat dan jenis vaksin apa saja yang wajib diberikan untuk menjaga kesehatan kucing Anda.',
    content: `Vaksinasi adalah salah satu langkah terpenting dalam menjaga kesehatan kucing Anda.\n\n## Vaksin Wajib\n- **Vaksin F3/F4**: Melindungi dari Feline Panleukopenia, Calicivirus, dan Rhinotracheitis\n- **Vaksin Rabies**: Wajib diberikan mulai usia 3 bulan\n\n## Jadwal Vaksinasi\n- 8-9 minggu: Vaksin pertama\n- 12 minggu: Booster pertama\n- 16 minggu: Booster kedua\n- Setiap tahun: Booster tahunan`,
    thumbnail_url: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    author: 'Dr. Rina Wijaya',
    published: true,
    views_count: 1580,
    created_at: '2024-10-10',
  },
  {
    id: '5',
    title: 'Mengenal Hewan Langka di Indonesia',
    slug: 'hewan-langka-indonesia',
    category: 'Hewan Langka',
    excerpt: 'Indonesia memiliki keanekaragaman hayati yang luar biasa. Kenali beberapa hewan langka yang hanya bisa ditemukan di Indonesia.',
    content: `Indonesia adalah rumah bagi ribuan spesies hewan unik yang tidak dapat ditemukan di tempat lain di dunia.\n\n## Komodo\nKadal terbesar di dunia yang hanya ditemukan di Pulau Komodo dan sekitarnya.\n\n## Orangutan\nPrimata besar yang hidup di hutan hujan Kalimantan dan Sumatera.\n\n## Badak Jawa\nSalah satu mamalia paling langka di dunia dengan populasi kurang dari 80 ekor.\n\n## Jalak Bali\nBurung endemik Bali yang terancam punah dengan bulu putih bersih yang cantik.`,
    thumbnail_url: 'https://images.unsplash.com/photo-1474511320723-9a56873571b7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    author: 'Ahmad Fauzi',
    published: true,
    views_count: 3200,
    created_at: '2024-10-15',
  },
  {
    id: '6',
    title: 'Konservasi Satwa Liar: Peran Kita Semua',
    slug: 'konservasi-satwa-liar',
    category: 'Konservasi Hewan',
    excerpt: 'Bagaimana kita bisa berkontribusi dalam upaya konservasi satwa liar di Indonesia? Simak langkah-langkah sederhana yang bisa dilakukan.',
    content: `Konservasi satwa liar adalah tanggung jawab kita bersama.\n\n## Edukasi\nPelajari tentang hewan-hewan yang terancam punah dan sebarkan kesadaran.\n\n## Donasi\nDukung organisasi konservasi yang terpercaya.\n\n## Tidak Membeli Hewan Liar\nHindari membeli hewan liar yang ditangkap secara ilegal.\n\n## Jaga Lingkungan\nKurangi penggunaan plastik dan jaga kelestarian hutan.`,
    thumbnail_url: 'https://images.unsplash.com/photo-1474511320723-9a56873571b7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    author: 'Budi Santoso',
    published: true,
    views_count: 980,
    created_at: '2024-10-20',
  },
]

export const mockCategories = [
  { id: 1, name: 'Kucing', slug: 'kucing', icon: '🐱', color: 'bg-brand-teal' },
  { id: 2, name: 'Anjing', slug: 'anjing', icon: '🐶', color: 'bg-brand-green' },
  { id: 3, name: 'Burung', slug: 'burung', icon: '🦜', color: 'bg-brand-purple' },
  { id: 4, name: 'Kelinci', slug: 'kelinci', icon: '🐰', color: 'bg-brand-blue' },
  { id: 5, name: 'Hamster', slug: 'hamster', icon: '🐹', color: 'bg-brand-yellow' },
  { id: 6, name: 'Ikan', slug: 'ikan', icon: '🐠', color: 'bg-blue-400' },
  { id: 7, name: 'Reptil', slug: 'reptil', icon: '🦎', color: 'bg-brand-orange' },
]

export const articleCategories = [
  'Semua',
  'Perawatan Hewan',
  'Kesehatan Hewan',
  'Tips Adopsi',
  'Hewan Langka',
  'Konservasi Hewan',
]
